apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: www
  labels:
      stefanmuraru.com/service: www
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: www
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

