apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    stefanmuraru.com/service: www
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      stefanmuraru.com/service: www
  template:
    metadata:
      labels:
        stefanmuraru.com/service: www
    spec:
      imagePullSecrets:
        - name: docker-io-credentials
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 15
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 15
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: stefanmuraru.com/service
                      operator: In
                      values: ["www"]
                topologyKey: stefanmuraru.com/host
      containers:
        - name: dashboard
          image: murarustefaan/www
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 2
            successThreshold: 1
