apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    stefanmuraru.com/service: www
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    stefanmuraru.com/service: www
