apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: www
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "www"
      images:
        - alias: www
          imageName: murarustefaan/www:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            kustomize:
              name: murarustefaan/www
